### ISSUE TITLE
请问可否将此仓库拆分为两个仓库？

### ISSUE THREAD

**Issue by chsbuffer** [AOSP-11/vendor_xiaomi#1]
如果往设备树中加入 Mi MIX 2 会对版本控制造成额外负担，
请求将此仓库拆分为 ``vendor_xiaomi_msm8998`` 和 ``vendor_xiaomi_sagit`` 两个仓库

**Comment by cooluc** [comment]
xiaomi/sagit  & xiaomi/chiron 都屬於固定blobs，因爲MIUI不再刷新msm8998裝置的固件。如果使用這個repo 為chiron構建rom，我們應該往這個repo增加chiron blobs支援，而不是將其分離。

**Comment by chsbuffer** [comment]
感谢解答，我会关闭次议题
此组织名称是专为 sagit，
简介中注明 msm8998 设备，
是否考虑创建 chiron 设备树、接受 chiron blob？

**Comment by sbwml** [comment]
> 感谢解答，我会关闭次议题
> 此组织名称是专为 sagit，
> 简介中注明 msm8998 设备，
> 是否考虑创建 chiron 设备树、接受 chiron blob？

这个aosp 完全支持chiron，缺的只是chiron固有的blobs和设备树。xiaomi 8998 公共文件已完全抛出项目中。因为这个项目的原本意思是给小米6 手机做的。chiron 只需补全设备树和blobs 构建出来的rom 是和小米6一样 无错误体验安卓11.。

vendor_xiaomi  这个repo并不推荐机型与公共文件分开，建议fork 后单独git add chiron。

**Comment by chsbuffer** [comment]
我自己试过用此组织的添加 MIX 2 设备树和 vendor blobs，确实可以构建出稳定的系统。

这个组织名称(Android Open Source Project Sagit)里写着 sagit，是否可以把 MIX 2 添加到这个组织(AOSP-11)里？
具体就是可否 在这个组织内创建 chiron 设备树项目，在 vendor_xiaomi 项目添加 chiron blob

**Comment by chsbuffer** [comment]
还有问题，MIX 2 没有红外，在设备树移除 IR 相关代码后，hardware/custom/interface/cryptfshw 好像是红外的依赖，会在构建时报错，目前我是移除这个模块才能构建。
